# Generated by Django 5.1.7 on 2025-03-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translator', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignLanguageInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sign_language_inputs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
